version: '3.8'

services:
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./be/.env
    restart: unless-stopped
    networks:
      - history-network

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - history-network

networks:
  history-network:
    driver: bridge