import liBaiData from '../data/li_bai.json';
import liQingzhaoData from '../data/li_qingzhao.json';
import suShiData from '../data/su_shi.json';

export const CHARACTERS = [
	{id: 1, name: '李白', era: '唐朝', status: '日常状态', color: 'blue', events: liBaiData, image: 'images/libai/libai_cover.png', avatar: 'images/libai/libai_young.png', avatarYoung: 'images/libai/libai_young.png', avatarMiddle: 'images/libai/libai_middle.png', avatarOld: 'images/libai/libai_old.png', birthYear: 701, markerIcon: 'images/markers/libai/point.png', markerIconSelected: 'images/markers/libai/point_selected.png', biography: {birthDeath: '701年–762年（62岁）', birthPlace: '碎叶（今吉尔吉斯斯坦托克马克）/蜀中昌隆', ancestralHome: '陇西成纪（今甘肃天水）', familyBackground: '汉飞将军李广后裔，凉武昭王李暠九世孙', courtesyName: '字太白，号青莲居士，又号“谪仙”', spouses: '许氏（727–738，生子伯禽、女平阳）；刘氏（739–742，无子）；山东某氏（744–749，子颇黎）；宗氏（751–762，无子）', officialPositions: '翰林供奉（待诏），约一年余', exile: '长流夜郎（758–759遇赦）', burialPlace: '初葬当涂龙山，817年迁青山西麓'}},
	{id: 2, name: '李清照', era: '宋朝', status: '日常状态', color: 'blue', events: liQingzhaoData, image: 'images/liqingzhao/liqingzhao_cover.png', avatar: 'images/liqingzhao/liqingzhao_young.png', avatarYoung: 'images/liqingzhao/liqingzhao_young.png', avatarMiddle: 'images/liqingzhao/liqingzhao_middle.png', avatarOld: 'images/liqingzhao/liqingzhao_old.png', birthYear: 1084, markerIcon: 'images/markers/liqingzhao/point.png', markerIconSelected: 'images/markers/liqingzhao/point_selected.png', biography: {birthDeath: '1084年3月13日–约1155年（71岁）', birthPlace: '齐州章丘明水（今山东济南章丘区明水镇）', ancestralHome: '齐州章丘', familyBackground: '父李格非（苏门后四学士），母王氏（状元王拱辰孙女）', courtesyName: '自号易安居士', spouses: '赵明诚（1101–1129，金石学家，《金石录》作者）；张汝舟（1132，再嫁不足三月即离）', children: '无（赵明诚、李清照夫妇无后嗣）', officialPositions: '无', exile: '无', literaryAchievements: '“词别是一家”理论，“易安体”婉约派正宗，“千古第一才女”', representativeWorks: '《漱玉词》《金石录后序》《夏日绝句》《声声慢》《如梦令》《一剪梅》《武陵春》《题八咏楼》等', literaryStatus: '婉约词宗，与辛弃疾并称“济南二安”', burialPlace: '卒年及葬地不详，一说葬于杭州'}},
	{id: 3, name: '苏轼', era: '宋朝', status: '日常状态', color: 'blue', events: suShiData, image: 'images/sushi/sushi_cover.png', avatar: 'images/sushi/sushi_young.png', avatarYoung: 'images/sushi/sushi_young.png', avatarMiddle: 'images/sushi/sushi_middle.png', avatarOld: 'images/sushi/sushi_old.png', birthYear: 1037, markerIcon: 'images/markers/sushi/point.png', markerIconSelected: 'images/markers/sushi/point_selected.png', biography: {birthDeath: '1037年1月8日–1101年8月24日（66岁）', birthPlace: '眉州眉山县纱縠行苏宅（今四川眉山）', ancestralHome: '赵州栾城（今河北栾城）', familyBackground: '初唐大臣苏味道后裔，祖父苏序，父苏洵，母程氏', courtesyName: '字子瞻，一字和仲，号东坡居士', examinationAchievement: '嘉祐二年进士及第（第二名）；嘉祐六年制科入三等（百年第一）', officialPositions: '翰林学士、知制诰、礼部尚书；八典名郡（密、徐、湖、登、杭、颍、扬、定）', exile: '黄州（1080–1084）、惠州（1094–1097）、儋州（1097–1100）', spouses: '王弗（1054–1065，子苏迈）；王闰之（1068–1093，子苏迨、苏过）；王朝云（侍妾，1080–1096，子苏遁夭折）', burialPlace: '河南郏县钧台乡上瑞里（三苏坟）', posthumousTitle: '文忠', literaryStatus: '唐宋八大家之一，豪放派词宗，“诗、词、文、书、画”五绝全能'}},
];
